name: calendar_bridge_example
description: "Demonstrates how to use the calendar_bridge plugin."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  calendar_bridge:
    path: ../

  # UI and state management
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  flutter_riverpod: ^2.6.1
  
  # Date and time utilities
  timezone: ^0.10.1
  intl: ^0.20.2
  
  # Additional UI components
  flutter_colorpicker: ^1.1.0
  table_calendar: ^3.1.2
  
  # Utilities
  uuid: ^4.5.1
  collection: ^1.18.0
  url_launcher: ^6.3.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
